### ISSUE TITLE
Version 0.8.9 broke deserialization behavior

### ISSUE THREAD

**Issue by jonasbb** [netvl/xml-rs#223]
I noticed a [failing test](https://github.com/jonasbb/serde_with/actions/runs/4963933053/jobs/8883601683#step:10:312) in my CI. I am using `xml-rs` via `serde-xml-rs`. The breaking change occurred between v0.8.8 and v0.8.9. The problem also occurs in v0.8.10.

`main.rs`
```rust
fn main() {
    use serde::Deserialize;

    #[derive(Debug, PartialEq, Deserialize)]
    #[serde(rename_all = "lowercase")]
    enum Item {
        Foo(String),
    }

    // Deserialize this XML
    let items: Vec<Item> = serde_xml_rs::from_str(
        r"
<foo>a</foo>
<foo>b</foo>
",
    )
    .unwrap();

    let expected = vec![
        Item::Foo(String::from("a")),
        Item::Foo(String::from("b")),
    ];
    assert_eq!(expected, items);
}
```

`Cargo.toml`
```toml
[package]
name = "xml-rs-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde-xml-rs = "0.6.0"
xml-rs = "=0.8.9"
# The code runs fine with this version of xml-rs
# xml-rs = "=0.8.8"
```

One possible commit could be this https://github.com/netvl/xml-rs/commit/ae9d83b3aec66ed6d8ac9dd5746d33d523c858cc since it has something to do with multiple root elements.
